
package at.ac.tuwien.cn2010.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SuperPeerListenerService", targetNamespace = "http://client.cn2010.tuwien.ac.at", wsdlLocation = "http://127.0.0.1:1234/SuperPeerService?wsdl")
public class SuperPeerListenerService
    extends Service
{

    private final static URL SUPERPEERLISTENERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(at.ac.tuwien.cn2010.client.SuperPeerListenerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = at.ac.tuwien.cn2010.client.SuperPeerListenerService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:1234/SuperPeerService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:1234/SuperPeerService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SUPERPEERLISTENERSERVICE_WSDL_LOCATION = url;
    }

    public SuperPeerListenerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SuperPeerListenerService() {
        super(SUPERPEERLISTENERSERVICE_WSDL_LOCATION, new QName("http://client.cn2010.tuwien.ac.at", "SuperPeerListenerService"));
    }

    /**
     * 
     * @return
     *     returns SuperPeerListener
     */
    @WebEndpoint(name = "SuperPeerListenerPort")
    public SuperPeerListener getSuperPeerListenerPort() {
        return super.getPort(new QName("http://client.cn2010.tuwien.ac.at", "SuperPeerListenerPort"), SuperPeerListener.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SuperPeerListener
     */
    @WebEndpoint(name = "SuperPeerListenerPort")
    public SuperPeerListener getSuperPeerListenerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.cn2010.tuwien.ac.at", "SuperPeerListenerPort"), SuperPeerListener.class, features);
    }

}
