
package at.ac.tuwien.cn2010.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SuperPeerListener", targetNamespace = "http://client.cn2010.tuwien.ac.at")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SuperPeerListener {


    /**
     * 
     * @return
     *     returns java.util.List<at.ac.tuwien.cn2010.client.SuperPeerInformationTransferObject>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSuperPeers", targetNamespace = "http://client.cn2010.tuwien.ac.at", className = "at.ac.tuwien.cn2010.client.GetAllSuperPeers")
    @ResponseWrapper(localName = "getAllSuperPeersResponse", targetNamespace = "http://client.cn2010.tuwien.ac.at", className = "at.ac.tuwien.cn2010.client.GetAllSuperPeersResponse")
    public List<SuperPeerInformationTransferObject> getAllSuperPeers();

}
